### ISSUE TITLE
Vendor directly is not handled correctly

### ISSUE THREAD

**Issue by cam-stitt** [matryer/moq#10]
From what I can tell, I cannot get it to run successfully when I am using a vendor directory. Here is an example result, I had to redact some paths:

<img width="1085" alt="screen shot 2017-02-13 at 12 00 36 pm" src="https://cloud.githubusercontent.com/assets/186643/22868683/4a3eaaf4-f1e4-11e6-8bf9-af91eac61e53.png">

**Comment by matryer** [comment]
Yeah - imports are confusing to moq... seems like https://github.com/matryer/moq/issues/6 is the real issue
