### ISSUE TITLE
Don't panic on nil callback?

### ISSUE THREAD

**Issue by abuchanan-nr** [matryer/moq#104]
What if instead of panicing on a nil `...Func` value, you just return the zero values?

Sometimes our tests don't need to return anything, we just want to capture and verify the calls. The `mock.calls` data structure is great for that, but adding empty implementations of `...Func` adds boilerplate.

**Comment by matryer** [comment]
The question is whether people will be surprised by what's going on or not. What do you think?

**Comment by breml** [comment]
I think it is an idea worth exploring, but if added to `moq`, it should be an opt-in feature which does not change the current default behavior.

See also #36

**Comment by matryer** [comment]
I would be open to a PR that added this as a flag options. `-defaults` or similar.

**Comment by breml** [comment]
I have a situation, where this feature would be beneficial for me, so I am interested in having this.

See also the (quite old) PR #96 for a potential implementation.

**Comment by Streppel** [comment]
Came here looking for this. As far as I can see this hasn't been implemented yet, right?

**Comment by sudo-suhas** [comment]
Moq now supports a `-stub` flag to support this use-case. Example of generated code when flag is specified:
https://github.com/matryer/moq/blob/83ab8dd79f4cd81ed605de6b758d595889103053/pkg/moq/testpackages/channels/queuer_moq.golden.go#L57-L74
