### ISSUE TITLE
Customizing generated mock name through an optional flag

### ISSUE THREAD

**Issue by pdrum** [matryer/moq#106]
Especially if one decides to gather all generated mocks in one package like `mocks`, there can be name clashes. (for example consider the case when there are two `Client` interfaces in the code base and both are them are being mocked). For avoiding those name clashes, of course there is a workaround. One can alias the types that are going to be mocked in the `mocks` package and then generate mocks for those aliased types. But that requires exposing those aliased types from `mocks` package which leads to confusion IMO. 

For solving the aforementioned problem I am asking if there can be a flag called `name` indicating name of the mock struct that moq generates.

**Comment by sudo-suhas** [comment]
I had the very same requirement but I don't think it can be supported without breaking backward compatibility since `moq` allows specifying multiple interfaces to generate mocks for. So I forked this repo and made minor modifications to support the same - https://github.com/sudo-suhas/moqit
