### ISSUE TITLE
Start using semantic versioning

### ISSUE THREAD

**Issue by Streppel** [matryer/moq#137]
Hey @matryer, first of all thank you, love your work here!

Have you thought about semver tagging the project for enhanced control over versions?

**Comment by breml** [comment]
I would like additionally to propose official releases of `moq` for easier installation. This process can be automated pretty well with https://github.com/goreleaser/goreleaser.

**Comment by matryer** [comment]
Yeah this is a good point—I’ll do this

**Comment by matryer** [comment]
OK @Streppel @breml Check that out... we have some releases now https://github.com/matryer/moq/releases

**Comment by breml** [comment]
@matryer Thank you very much, this is really appreciated.
