### ISSUE TITLE
Optionally generating mock tests

### ISSUE THREAD

**Issue by jimah** [matryer/moq#14]
Hello!

We're using moq successfully for our internal company services and loving it.

Our continuous integrations system forces a strict test coverage threshold, this has lead to us repeatedly writing small tests for the generated mocks, a process that could be automated. 

Is this something that could be considered for the `moq` package itself? An optional flag that would generate `_test` files for the mocks. We're happy to contribute towards this goal.

Thank you

**Comment by matryer** [comment]
@jimah Thanks, glad it's useful

Yeah OK - it should be pretty easy to do. Maybe `moq -tests...` flag?

**Comment by jimah** [comment]
That sounds ideal :)

**Comment by matryer** [comment]
@jimah Do you fancy having a go at this?

**Comment by matryer** [comment]
@jimah I wonder if it makes more sense for you to generate your mocks into `_test.go` files instead? I've gone off the idea of having dedicated test code for mock code, because they're getting tested through your actual code anyway, and it'll just end up being more noise and more stuff to run.
