### ISSUE TITLE
Released version of moq does not print correct version

### ISSUE THREAD

**Issue by breml** [matryer/moq#143]
I just downloaded the pre-compiled version of `moq` v0.2.0 from Github releases and it does not print the correct version:

```shell
$ moq -version
moq version dev
```

Expected:

```shell
$ moq -version
moq version v0.2.0
```

**Comment by sudo-suhas** [comment]
I had used goreleaser to build the binaries. Not sure why the version was not passed in using `ldflags`. Steps followed:

```
$ git tag --annotate --message="Release v0.2.0" v0.2.0
$ goreleaser release --rm-dist
```

@matryer Is there anything wrong with the above steps?

**Comment by matryer** [comment]
Those commands are slightly different to what I use, see the README.md.

But I don't know why that would make a difference. Maybe @caarlos0 has an idea?

**Comment by caarlos0** [comment]
Hey!

Your goreleaser config is setting Version (capital V) instead of version... probably that's the issue...

**Comment by matryer** [comment]
@caarlos0 Thanks for helping :) So it should be `- -X main.Version={{.version}}`?

**Comment by matryer** [comment]
@caarlos0 Thanks for your help. That's it, the variable is unexported in main and they don't match.

**Comment by matryer** [comment]
Verified, this is fixed. Thanks everyone.

```
➜  moq_0.2.1_macOS_x86_64 ./moq -version
moq version 0.2.1
```
