### ISSUE TITLE
Add option to specify package comment conforming to the standard format?

### ISSUE THREAD

**Issue by nahojer** [matryer/moq#154]
Thank you for letting me generate readable and simple mocks! 

Is it possible to get an option to do something like this?

```go
// Package mypkg ...
//
// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mypkg
```

The reason for wanting this is to suppress linters without having to clutter my codebase with config files.

**Comment by sudo-suhas** [comment]
But linters ignore generated files. From the [docs of `golangci-lint`](https://golangci-lint.run/usage/configuration/):

```yaml 
  # ... there is no need to include all autogenerated files, we confidently recognize
  # autogenerated files. If it's not please let us know.
```

**Comment by nahojer** [comment]
I use [staticcheck](https://staticcheck.io/) which have deprecated file ignore patterns in config files and doesn't seem to have any intention to add this to their linter. For now I have just disabled the package comment rule (ST1000), although I would really like the rule for non-generated/test files

Maybe it's time to consider golangci-lint at some point... the thing is, I do really like staticcheck when disregarding not having this feature.
