### ISSUE TITLE
Publish moq to the AUR

### ISSUE THREAD

**Issue by cloudlena** [matryer/moq#156]
It would be great to see `moq` published on Arch Linux' [AUR](https://aur.archlinux.org/).

Are there any plans to do so? Should I take care of it?

**Comment by sudo-suhas** [comment]
What are the changes necessary for publishing this on AUR?

**Comment by mastertinner** [comment]
There are no changes needed. We just need to create a separate repo in the AUR with a `PKGBUILD` file. I created one for [Nancy](https://github.com/sonatype-nexus-community/nancy) as you can see here: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=nancy-bin

**Comment by sudo-suhas** [comment]
@matryer what do you think?

**Comment by cloudlena** [comment]
@matryer and @sudo-suhas, I'm happy to create the AUR package and maintain it. Should I do so, or would you like to take care of it?

**Comment by cloudlena** [comment]
I just created https://aur.archlinux.org/packages/moq-bin
If any of you would like to take over the ownership, I'm happy to transfer it to you.
