### ISSUE TITLE
Running moq  cmd causes `couldn't load source package error`

### ISSUE THREAD

**Issue by joegasewicz** [matryer/moq#164]
Getting the following error:
```
couldn't load source package: couldn't run 'go': fork/exec /usr/local/Cellar/go/1.17.5/libexec/bin/go: not a directory
```

When running:
` moq -out handlers/mock_clients.go handlers/clients.go AreaApiClient`

If i run `go generate ./...` & include the generate comments it works fine.

Using MacOS with Montery
My `$GOPATH` is `/Users/$USER/go`
My `$GOROOT` is `/usr/local/Cellar/go/1.17.5/libexec`

**Comment by sudo-suhas** [comment]
Could you try running ` moq -out handlers/mock_clients.go handlers AreaApiClient`? The command is expecting a directory, see https://github.com/matryer/moq#usage.
