### ISSUE TITLE
Moq fails generating mocks in go 1.18 

### ISSUE THREAD

**Issue by tprebs** [matryer/moq#166]
I switch from go version `1.17.8` to `1.18` and now  Moq is now failing with 
`internal error: package "errors" without types was imported from "...."`. After a quick dig around its seems to be caused by the current version of `x/tools` not playing nicely with 1.18.  (https://github.com/golang/go/issues/49164)

I have bumped xtools to 0.1.9 and this has resolved the issue

**Comment by jozuenoon** [comment]
Same here, hope we got a new release soon?

**Comment by peterhellberg** [comment]
I've resorted to `git clone --single-branch -b update_x_tools https://github.com/slagiewka/moq.git && cd moq && go install` in our Dockerfile that is used when calling `go generate`.

**Comment by matryer** [comment]
Please try the latest release, and let me know.

**Comment by peterhellberg** [comment]
@matryer I've updated our Dockerfile, and the new release seems to be working as it should. 👍🏻
