### ISSUE TITLE
Generate mock for external library 

### ISSUE THREAD

**Issue by alexisvisco** [matryer/moq#172]
Hi, I am wondering if it's possible to generates mock for external library, if it's possible how to do it ?

**Comment by breml** [comment]
In some cases, I used type aliases for this use case like this:

```Go
package myreader

import "io"

//go:generate moq -out reader_mock.go . Reader

type Reader = io.Reader
```

**Comment by matryer** [comment]
thanks @breml - another option is to copy the interface into your own project. This isn't a hack per se, some people like to do this anyway as it allows them to provide multiple implementations of something in their project.
