### ISSUE TITLE
Moq ignores package names of arguments of generic types

### ISSUE THREAD

**Issue by lindebergue** [matryer/moq#177]
When mocking a method with a generic type, moq ignores package names of type arguments.

This works:
```go
package example

//go:generate moq -skip-ensure -stub -rm -out mocks.go . Foo:FooMock

type Bar[T any] struct{}

type Foo interface {
	Foo(bar Bar[Type])
}
```

But this does not:
```go
package example

//go:generate moq -skip-ensure -stub -rm -out mocks.go . Foo:FooMock

import "path/to/pkg"

type Bar[T any] struct{}

type Foo interface {
	Foo(bar Bar[pkg.Type])
}
```

The generated code instantiates `Bar` as `Bar[Type]` instead of `Bar[pkg.Type]`, failing to compile:

```go
// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package example

import (
	"sync"
)

type FooMock struct {
	// FooFunc mocks the Foo method.
	FooFunc func(bar Bar[Type])

	// calls tracks calls to the methods.
	calls struct {
		// Foo holds details about calls to the Foo method.
		Foo []struct {
			// Bar is the bar argument value.
			Bar Bar[Type]
		}
	}
	lockFoo sync.RWMutex
}
```

I've tried workarounds like dot imports and type aliases, but got the same results. If `Bar` type is a built-in like `map`, it works fine.
moq version `v0.2.7`.

**Comment by matryer** [comment]
Hmm, yeah I guess it's not 'generics ready'. I wonder if you fancy submitting a failing test in a PR?

**Comment by ben-haverly-cfa** [comment]
Hey, I actually ran into the same issue. Was just curious if there was any movement on this?

**Comment by xsteadfastx** [comment]
i read the changelog of 0.3.0 that said it got generics support. tested it today. still running into this problem.

**Comment by xsteadfastx** [comment]
i created a failing test through #177
