### ISSUE TITLE
Write the mock in the corresponding _test package

### ISSUE THREAD

**Issue by fvosberg** [matryer/moq#21]
Hi Mat, 

at first, thank you very much for this great package. Unfortunately I'm a little bit struggling with getting started, so I would like to help improve the documentation with my misunderstanding ;).

I've created a little example: https://github.com/fvosberg/moqtest

When I try

```
//go:generate moq -out service_moq_test.go -pkg moqtest_test github.com/fvosberg/moqtest Service
```

Then I get
```
open github.com/fvosberg/moqtest: no such file or directory
```

And when I use 

```
//go:generate moq -out service_moq_test.go -pkg moqtest_test . Service
```
I get on ```go test```
```
service_moq_test.go:8:2: local import "." in non-local package
```

Am I using the package wrong, or is this case not implemented? I would really appreciate some help and when it is not implemented right now, I would really love help implementing it.

Cheers
Fredi

**Comment by matryer** [comment]
Hmm.. looks like you've found a bug.

**Comment by matryer** [comment]
@fvosberg I think I've fixed this... please install the latest with `go get -u github.com/matryer/moq`, and run `go generate` in your moqtest project again.

I also took your files and added them to this repo to act as the test. Let me know if that's a problem.

**Comment by fvosberg** [comment]
Thanks for your fast fix, I'll check that out later on.
