### ISSUE TITLE
Moq fails when encountering new golang idioms

### ISSUE THREAD

**Issue by arkadiuszos4chain** [matryer/moq#224]
Hello ;-)

The current version of `moq` fails when encountering certain statements, such as:
```go
for range 5 {
  // ...
}
```
which results in the following error:
```
couldn't load source package: sample.go:110:12: cannot range over 5 (untyped int constant)
```
I prepared a PR to bump the `go` and `golang.org/x/tools` version: [#223](https://github.com/matryer/moq/pull/223)

**Comment by arkadiuszos4chain** [comment]
@sudo-suhas

**Comment by sudo-suhas** [comment]
I was a bit busy yesterday and could not release a new version from mobile. Will create a new release today.

**Comment by sudo-suhas** [comment]
Fixed via https://github.com/matryer/moq/releases/tag/v0.4.0 🎉

**Comment by arkadiuszos4chain** [comment]
Great! Thank you
