### ISSUE TITLE
-fmt command to specify formats `gofmt` or `goimports`

### ISSUE THREAD

**Issue by ntoljic** [matryer/moq#27]
More a request for improvement than a bug report.

**Request:**  

After generating the moq files, run them through `gofmt`.

**Use case:**  

When manually changing a generated file, saving it causes gofmt to run, leading to a bigger diff in version control. I know that I could a) simply avoid changing the file manually and instead re-generate it or b) perform the changes in an editor that does not automatically run `gofmt`, or c) add a pre-commit hook to run `gofmt` on all .go files.  
It would be nice to have nonetheless and solve a minor pain point for me :)

**Comment by matryer** [comment]
Yes!

**Comment by matryer** [comment]
I just came to the project to add this very issue.

**Comment by matryer** [comment]
@ntoljic done. Can you test it for me please?

**Comment by ntoljic** [comment]
@matryer The code itself is formatted as expected, but the imports section gets rearranged.

Generated code before and after running gofmt:

```diff
 import (
 	"database/sql"
+	"sync"
+	"time"
+
 	"github.com/jmoiron/sqlx"
 	"gogs.dev/wemit/xpo-api/cmn"
 	"gogs.dev/wemit/xpo-api/models"
-	"sync"
-	"time"
 )

```
I suspect that this is due to the custom importer introduced as a fix for https://github.com/matryer/moq/issues/6.

**Comment by matryer** [comment]
Part of formatting code does rearrange the imports, so that’s expected. But it should be consistent. Make sense?

**Comment by ntoljic** [comment]
I understand that gofmt also rearranges imports in a deterministic way. What I am saying is that the generated moq file arranges them in a different deterministic way.

Suppose we have a generated file `a.moq.go`, with imports b and c (in this order).  
When I run `gofmt` on `a.moq.go` the imports get changed to c and b (the imports stay the same, but the order changes).  
The next time I re-generate `a.moq.go`, it has again imports for b and c (in the initial order).

This way, If I am not careful, I keep committing the same pair of changes over and over again.

**Comment by matryer** [comment]
So the question I have is this: Why goes `go/format` rearrange the imports in a different way to `go fmt` and can you prove that somehow in a failing test?

**Comment by ntoljic** [comment]
The answer is, it doesn't.
I found an article explaining the difference between gofmt and goimports.
The latter groups, adds and removes  imports, while the former only sorts
the imports alphabetically.

http://goinbigdata.com/goimports-vs-gofmt/

It seems that the vscode-go plugin for visual studio code uses goimports
(actually it uses goreturns by default, but for this issue there's no
difference between the two).

So I guess that with your custom importer, it makes no sense to use
goimports instead of gofmt for the formatting?

On 2 Aug 2017 4:59 p.m., "Mat Ryer" <notifications@github.com> wrote:

So the question I have is this: Why goes go/format rearrange the imports in
a different way to go fmt and can you prove that somehow in a failing test?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/matryer/moq/issues/27#issuecomment-319699119>, or mute
the thread

**Comment by matryer** [comment]
I don't think we can trust goimports for generated code because it can get confused. But I'd be happy to add an option so you can specify it. How does that sound?

Something like:

moq -fmt goimports

**Comment by ntoljic** [comment]
That'd be perfect! :)
On 3 Aug 2017, at 09:11, Mat Ryer <notifications@github.com> wrote:

I don't think we can trust goimports for generated code because it can get confused. But I'd be happy to add an option so you can specify it. How does that sound?

Something like:

moq -fmt goimports

**Comment by sudo-suhas** [comment]
@matryer Do let me know if you are no longer interested in adding this feature(it has been open for a couple of years now). Otherwise, I am thinking of integrating https://github.com/golang/tools/tree/master/imports to implement it.

**Comment by matryer** [comment]
@sudo-suhas One simple solution for this kind of thing is to just process the file _after_ moq has generated it. 

For example, it's you can format Go code very easily like this:

```
gofmt -w ./file.go ./file.go
```

I wonder if this approach should be recommended, rather than adding any formatting to moq itself?

**Comment by sudo-suhas** [comment]
Personally I like that `moq` formats the source code. I think this is what the majority of users would want. So the right balance of good default and less bloat _could_ be to instead suggest that if you need it to be formatted differently, you should just run it yourself. I think the majority of Go users would have the `goimports` in their `PATH` somewhere.

**Comment by breml** [comment]
I also like that `moq` formats the source code.

I am the maintainer of [pigeon](https://github.com/mna/pigeon) and there we use `golang.org/x/tools/imports` to format and adjust the Go imports. see: https://github.com/mna/pigeon/blob/master/main.go#L145-L165

So I suggest to use `golang.org/x/tools/imports` directly built into `moq` instead of relying on the user having `goimports` in the `PATH`.

**Comment by sudo-suhas** [comment]
@breml Why do you think integrating `imports` is better than something like `moq ... && goimports ...`? I think it is a fair argument to say that `moq`'s core concern should be about generating a mock and formatting is less important. At this point I haven't made up my mind either way, just want to uderstand your perspective a bit better.

**Comment by breml** [comment]
The problems I see with `moq ... && goimports ...` are:

1. Does not work well with `go generate`
2. Is different on *nix and Windows

In regards to 1., I normally use `moq` similar to this:

```
package moqtest

//go:generate moq -pkg mockmyinterface -out mockmyinterface/myinterface.go . MyInterface

type MyInterface interface {
	myMethod() bool
}
```

This does not work with `moq ... && goimports ...`, because `go:generate` does not act like a shell (where `&&` is understood) but adds everything as arguments after the initial command, so you end up with the following error:

```
$  go generate .
cannot find interface &&
moq [flags] destination interface [interface2 [interface3 [...]]]
  -out string
        output file (default stdout)
  -pkg string
        package name (default will infer)
moqtest.go:3: running "moq": exit status 1
```

In regards to 2. you will have to explain the usage for *nix and Windows and I don't think, there is a `go:generate` line, that works for both, *nix and Windows.

**Comment by sudo-suhas** [comment]
Thanks @breml, that helps. It _is_ possible to do something like `//go:generate sh -c "tool < file.txt > file.go"` but I think this is adding complexity and affecting cross-platform support.

**Comment by sudo-suhas** [comment]
@breml I have made a PR for this change in #117, please check it out

**Comment by breml** [comment]
@sudo-suhas thanks for the ping, I will try to have a look at this in the next few days.

**Comment by breml** [comment]
@sudo-suhas I like your PR #117, thanks for the effort.
