### ISSUE TITLE
How does one mock a third-party package?

### ISSUE THREAD

**Issue by zmb3** [matryer/moq#28]
The examples in the readme all show how to generate a mock for an interface you own.

Is it possible to generate a moq for a standard library interface?  Or for another interface on your gopath?

Nothing I try seems to work:
- `moq . io.Reader`
- `moq . io/Reader`
- `moq -pkg io . Reader`

**Comment by matryer** [comment]
The dot is the file, so technically you could point to the file that contains io.Reader, but it's a use case that wasn't accounted for.

**Comment by bancek** [comment]
You can create a wrapper interface in your package and then moq that interface.

Example:

```
package yourpackage

import "io"

type IoReader interface {
  io.Reader
}
```

```
moq -out ioreader_moq_test.go . IoReader
```

**Comment by breml** [comment]
For 3rd party packages (not the standard library), this works as well:

```
moq -out person_store_mock.go -pkg mock $(go list -f '{{.Dir}}' github.com/matryer/moq/example) PersonStore
```
