### ISSUE TITLE
go:generate seems to ignore -pkg flag 

### ISSUE THREAD

**Issue by Jasrags** [matryer/moq#30]
First off, thanks for the cool tool, it's a time saver.
I have noticed that when generating mocks via `go generate <pkg>` and the file to be mocked having
```//go:generate moq -out ./mock/service_moq.go -pkg mock . Service```

The generated file has the original package name of `service` and not `mock` as expected. When running `moq -out ./mock/service_moq.go -pkg mock . Service` from the service directory the generated file package is set to `mock` as expected. 

Let me know if you need any further info from me.

**Comment by matryer** [comment]
Hmm weird, @Jasrags I wonder if you could submit a PR with a test that fails demonstrating this?

**Comment by Jasrags** [comment]
Strange, now that i run it again it works as expected.

**Comment by matryer** [comment]
hmmm... probably something slightly different the first time you did it.

**Comment by matryer** [comment]
Let me know if you see it again.

**Comment by Jasrags** [comment]
Thanks @matryer! Super interested in https://github.com/matryer/moq/issues/32 BTW. Thanks for the tool.

**Comment by matryer** [comment]
Fancy helping with it?

**Comment by Jasrags** [comment]
If i can, i have a fork already and spent a few minutes on it just now. I'll keep on looking.
