### ISSUE TITLE
Followed instructions in blog but moq seems to be doing something else

### ISSUE THREAD

**Issue by rnduldulaojr** [matryer/moq#33]
I tried to generate a mock object from this file:
------------------------cache.go-----------------------
package impls

//go:generate moq -out cache_mock_test.go . Cache

//Cache --
type Cache interface {
	//basic ops
	Store(key, value string) error
	StoreWithTTL(key, value string, ttl int64) error
}`

Tried running go generate:

 % go generate

errors.go:15:40: cannot use codes.AlreadyExists (constant 6 of type google.golang.org/grpc/codes.Code) as google.golang.org/grpc/codes.Code value in argument to grpc.Errorf
moq [flags] destination interface [interface2 [interface3 [...]]]
  -out string
        output file (default stdout)
  -pkg string
        package name (default will infer)
cache.go:3: running "moq": exit status 1

I also tried running moq on the command line, still got the error above.  Is this really working?

**Comment by rnduldulaojr** [comment]
I ran the example, and it works well.     I put my cache.go in a new directory and I was able to generate the mock file.   It does seem to have a problem with my errors.go file which contains global error declarations.  Running go build on my library though does not detect the same problem moq detects : errors.go:15:40: cannot use codes.AlreadyExists (constant 6 of type google.golang.org/grpc/codes.Code) as google.golang.org/grpc/codes.Code value in argument to grpc.Errorf

**Comment by rnduldulaojr** [comment]
Hi again, so basically what our tool is telling me is to replace all my grpc.Errorf from this:

ErrAccountExistsPending = grpc.Errorf(codes.AlreadyExists, "account already exists with status: PENDING")

which is clear and readable

to this:

ErrAccountExistsPending = grpc.Errorf(6, "account already exists with status: PENDING")

-- which forces me to lookup all the constant declarations

before being able to generate a mock.

**Comment by rnduldulaojr** [comment]
I am running a modified version of your moq.go, had the following commented out to make it work for me:

		conf := types.Config{Importer: newImporter(m.src)}
		tpkg, err := conf.Check(m.src, m.fset, files, nil)
		if err != nil {
			**//return err**
		}

**Comment by matryer** [comment]
It might be that the custom importer was finding the wrong package. Do you have older versions installed too?

**Comment by sudo-suhas** [comment]
Closing as stale.
