### ISSUE TITLE
go/format error

### ISSUE THREAD

**Issue by djui** [matryer/moq#37]
When executing `moq` with (roughly) the following command line, I get a `go/format` error:

```
$ moq -out mocks_test.go -pkg my/package/repo/path . Repository
go/format: 4:15: expected ';', found '.'
```

I am not sure from which file this error comes from, but at line 4 of the file where the `Repository` interface is declared, there is neither a `;` nor `.`.

**Comment by chrishulbert** [comment]
I have this issue.

Here's my suggestion: try editing ~/go/src/matryer/moq/main.go, finding the line containing `fmt.Errorf("go/format`, change it to `return fmt.Errorf("go/format: %s | %s", err, string(buf.Bytes()))`, and run `go build` (from the moq folder).

Then find the moq commandline by searching for `go:generate` in your project, then run `../../moq ...etc...` in your project's folder. This will let you see the code that moq is generating that is breaking the formatter, and will let you know which types are causing it to fail.

In my case it's generating `*invalid type` in the code, which I don't have the answer to yet.

**Comment by sudo-suhas** [comment]
A couple of changes have been introduced in relation to this issue. For one, we are now checking errors on loading the package info (70fed06e) which should fail fast with appropriate error message returned from golang.org/x/tools/go/packages. Additionally, a [new formatter option, `noop`](https://github.com/matryer/moq#usage) can be used to print the generated source code without attempting to format it (which could fail when the generated code is not valid). Hope that helps.
