### ISSUE TITLE
Use function or mock name for panic prefix

### ISSUE THREAD

**Issue by djui** [matryer/moq#41]
I think using the function or mock type name as panic prefix is more Go idiomatic, even though I might understand there is some "branding value". For a reader of the panic that was not involved in the mock generator phase (larger teams) it can be confusing to recover where or what `moq` in this context is.

I would like to suggest changing the following (the "branding value" is still given in the auto-generated header):

https://github.com/matryer/moq/blob/c80e9a745bfcdd103a9c5d29e6860c7e95b43f6e/pkg/moq/template.go#L62

```diff
-panic("moq: {{$obj.InterfaceName}}Mock.{{.Name}}Func is nil but {{$obj.InterfaceName}}.{{.Name}} was just called") 
+panic("{{$obj.InterfaceName}}Mock: {{.Name}}Func is nil but {{.Name}} was just called")
```

**Comment by matryer** [comment]
Not interested in branding value, I just want to make the experience clear.

**Comment by djui** [comment]
Sorry if that comment gave a negative connotation. I just believed that the `Mock` suffix would reflect more honestly which subject being exercised: was it `moq`, the binary? or the generate `Mock`, by `moq`.

**Comment by matryer** [comment]
Yeah makes sense.
