### ISSUE TITLE
Invalid import path for destination package

### ISSUE THREAD

**Issue by ncsibra** [matryer/moq#49]
It looks like moq generating non compilable  code in case it has to add an import to the destination package.
Here's some code to reproduce: 
https://github.com/ncsibra/moqtest
Run `go test ./...`  from the root, which gives an `it/storage_mock_test.go:7:2: local import "../storage" in non-local package` error.

I want to write some integration test in a separate package and I want to generate the mocks with moq.
The package to mock contains multiple interfaces and one of the interface refers to an other in the same package, which cause the problem.
Based on the documentation we need to add a path as a destination, so in my case, [I added `../storage`](https://github.com/ncsibra/moqtest/blob/master/it/it_test.go#L3).
It generates the mock file without any problem, but does not resolve the correct package path, just simply adds the destination argument as an [import path](https://github.com/ncsibra/moqtest/blob/master/it/storage_mock_test.go#L7).
If I use an absolute path as destination the same happens.

I assume it's a bug and it should resolve to the correct import path.

**Comment by sudo-suhas** [comment]
@ncsibra I cloned the repo, ran `go generate ./...` and the mock was generated correctly as far as I can tell. So I am closing this issue Here's the diff after running generate:

```diff
diff --git a/it/storage_mock_test.go b/it/storage_mock_test.go
index cc6b054..a6736dd 100755
--- a/it/storage_mock_test.go
+++ b/it/storage_mock_test.go
@@ -1,10 +1,10 @@
-// Code generated by moq; DO NOT EDIT
+// Code generated by moq; DO NOT EDIT.
 // github.com/matryer/moq

 package it

 import (
-       "../storage"
+       "github.com/ncsibra/moqtest/storage"
        "sync"
 )

@@ -12,19 +12,23 @@ var (
        lockDBMockGet sync.RWMutex
 )

-// DBMock is a mock implementation of DB.
+// Ensure, that DBMock does implement storage.DB.
+// If this is not the case, regenerate this file with moq.
+var _ storage.DB = &DBMock{}
+
+// DBMock is a mock implementation of storage.DB.
 //
 //     func TestSomethingThatUsesDB(t *testing.T) {
 //
-//         // make and configure a mocked DB
+//         // make and configure a mocked storage.DB
 //         mockedDB := &DBMock{
 //             GetFunc: func() storage.Row {
-//                    panic("TODO: mock out the Get method")
+//                    panic("mock out the Get method")
 //             },
 //         }
 //
-//         // TODO: use mockedDB in code that requires DB
-//         //       and then make assertions.
+//         // use mockedDB in code that requires storage.DB
+//         // and then make assertions.
 //
 //     }
 type DBMock struct {
@@ -42,7 +46,7 @@ type DBMock struct {
 // Get calls GetFunc.
 func (mock *DBMock) Get() storage.Row {
        if mock.GetFunc == nil {
-               panic("moq: DBMock.GetFunc is nil but DB.Get was just called")
+               panic("DBMock.GetFunc: method is nil but DB.Get was just called")
        }
        callInfo := struct {
        }{}
```
