### ISSUE TITLE
moq errors with "cannot find package" looking for a path instead of a package name

### ISSUE THREAD

**Issue by iamtheddrman** [matryer/moq#52]
We have used moq for a few months now, but recently updated a few interfaces and needed to regenerate the mock objects. I ran the same command as before:
`moq -out ../testutils/test_interface.go . MessageSender`

This command was run from a subdirectory of our project, within the GOPATH folder. However, instead of generating the files as expected, it yields an error:
`cannot find package "C:\\Users\\username\\src\\{our_project_name}\\{folder_I_ran_from}`
followed by "no initial packages were loaded"

I actually copy/pasted the command from the last time I ran it, and am certain that I'm running it from the same directory. Has something changed w.r.t to Golang version requirements or the parameters that must be supplied? It looks like this command should run based on the current documentation.

I'm running Go 1.8.3 and a coworker is running 1.9, and we're both seeing the same issue.

**Comment by matryer** [comment]
What are you importing the package as?

**Comment by iamtheddrman** [comment]
The main package imports the package containing MessageSender with an alias. The directory from which I'm running moq contains the parent package which imports the "models" package containing MessageSender without an alias.

I've tried running from the main package directory using the actual package name and the aliased name. I also ran it from the parent package of the "models" package with and without the -pkg parameter, and ran it from the models package directory with and without the -pkg parameter. All of them yielded the same error message (obviously with different directories): 
`
cannot find package "C:\\Users\\username\\src\\{project}\\{parent}\\models" in any of:
 C:\Go\src\C:\Users\username\src\{project}\{parent]\models (from $GOROOT)
 C:\Users\username\src\C:\Users\username\src\{project}\{parent}\models (from $GOPATH)`

It's very odd that the current directory is getting concatenated in whole to the GOROOT and GOPATH directories, rather than just the relative directories.

**Comment by surjith** [comment]
same thing hapening to me as well

**Comment by matryer** [comment]
Can one of you please submit a PR with a new test that fails highlighting your issue? The trouble is, moq as a tool operates within each environment so it’s possible it’s different for different people.

**Comment by bguilder** [comment]
Just to bump this, I'm also getting the same `cannot find package` error with the current directory being appending to the GOPATH. Also seeing the same results from running the tests as above.

Recently switched over to running out of WSL. Maybe this could be the cause?

**Comment by warmans** [comment]
I think this is caused by GOPATH not being set. In recent versions of Go you don't need to set it anymore to build packages but Moq still seems to need it.
