### ISSUE TITLE
Generated files contain "TODO" strings which are searched by some editors/plugins and clutter search results

### ISSUE THREAD

**Issue by DanPallas** [matryer/moq#56]
Some IDEs, such as Goland, and plugins, such as Visual Studio Code's TODO Highlight, search your code for "TODO" in comments so they can display a list of outstanding TODO comments. It's not uncommon to search for "TODO" regardless of your dev environment. Files generated by moq contain comments with TODO and are displayed in these IDEs/plugins and clutter search results. 

Could moq either modify those comments to not include "TODO" or have a flag added to suppress them?

**Comment by matryer** [comment]
@DanPallas thanks for your idea - I would change this. Do you fancy submitting a PR?

**Comment by DanPallas** [comment]
Thanks for the response. I haven't looked at the source yet, but I should be able to put together a PR.

**Comment by breml** [comment]
@DanPallas It is not too hard to add a flag, just have a look at my PR #59, which does the same (will fix the merge conflict tomorrow, I waited for #58 to be merged).

**Comment by matryer** [comment]
Let's just remove the `TODO` altogether. @DanPallas Do you want to do a PR?

**Comment by pdrum** [comment]
@matryer I added a flag for it in https://github.com/matryer/moq/pull/65

**Comment by breml** [comment]
New PR to fix this is in #66.

**Comment by breml** [comment]
#66 is merged, this issue can be closed.
