### ISSUE TITLE
Missing imports in generated files

### ISSUE THREAD

**Issue by eikeCL** [matryer/moq#6]
There are no imports defined in the generated files.

**Comment by matryer** [comment]
I was thinking of running it through `goimports` - @ernesto-jimenez how have you tackled this in the past?

**Comment by ernesto-jimenez** [comment]
@matryer, it is a bad idea and I always avoid it with generated code.

goimports can add the wrong package when there are two packages in the GOPATH with the same name and similar signatures. Classical example is wanting `html/template` and goimports importing `text/template`.

Your program will generate different outputs depending on the contents of the user's GOPATH.

I have this solved in my `gogen` package. You can see how to implement it there.

**Comment by matryer** [comment]
@piotrrojek Can you look at this please?

**Comment by piotrrojek** [comment]
Yes, with pleasure.

**Comment by alecha** [comment]
Do you think there is a way to do it only for the packages in the std lib?

**Comment by johanbrandhorst** [comment]
What is the status of this? @piotrrojek

**Comment by martin-magakian** [comment]
@johanbrandhorst still not fix see unit test to demonstrate the problem #15

**Comment by matryer** [comment]
What happens if you run the output through goimports? If that works for most cases, it might be the solution - as it's much simpler.

**Comment by martin-magakian** [comment]
something like this ?
moq . MyInterface | goimports

**Comment by matryer** [comment]
I think piping it might be nice... @martin-magakian can you have a play with it and let me know what you think?

**Comment by martin-magakian** [comment]
Thanks for your answer @matryer

Moq output is an error (see below). Therefore I can't pipe that into goimports.
(Or maybe I'm not doing to correctly)

You can reproduce the problem very easily with my pull request:
```
go get github.com/martin-magakian/moq
cd github.com/martin-magakian/moq/package/moq/testdata/multipackage
moq -out MyInterface_test.go . MyInterface
```

Output:
> moq -out MyInterface_test.go . MyInterface
> MainPackage.go:3:8: could not import github.com/matryer/moq/package/moq/testdata/multipackage/subpackage (can't find import: )
> moq [flags] destination interface [interface2 [interface3 [...]]]
>   -out string
>     	output file (default stdout)
>   -pkg string
>     	package name (default will infer)

**Comment by matryer** [comment]
To have moq properly add imports, we'll have to properly manage this in the code. 

Technically, go generate commands should be dev time, so you can always just go into the file, and save it (assuming you have goimports on save setup) and 'manually' solve this for now.

**Comment by matryer** [comment]
I think I've solved imports... can you please confirm and let me know?

**Comment by martin-magakian** [comment]
Hi matryer,
I didn't spend enough time on it.
I now write the mock myself.

If you want to spend some time on it checkout: #15 unit test

**Comment by matryer** [comment]
Well Moq handles imports now, so please give it a try in the future. :)
