### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by pdrum** [matryer/moq#60]
If there is a recursive import in the code and the interface to be mocked is in one of the packages in the chain of recursive imports, moq will go into an infinite loop rather than generating an error.

**Comment by matryer** [comment]
What's a recursive import? Aren't cyclic dependencies forbidden in Go?

**Comment by pdrum** [comment]
@matryer Yes they are forbidden and that's a compile error, but in case someone runs moq when there is such an import in the code in the file that holds the interface to be mocked, moq will go into an infinite loop instead of printing some error and exiting.
