### ISSUE TITLE
Import aliases not maintained, cannot import multiple packages with same name

### ISSUE THREAD

**Issue by shousper** [matryer/moq#68]
We have an unfortunate case where we have packages with the same name imported:

```
package things

import (
	"context"

	pclient "github.com/example/client"
	mclient "github.com/micro/go-micro/client"
)

//go:generate moq -out client.mock.go . Client

type Client interface {
	GetByID(ctx context.Context, in *pclient.Client, opts ...mclient.CallOption) (*pclient.Response, error)
}
```

The generated code doesn't retain the import aliases meaning we have to find/replace a bunch of code post-generate. Any chance moq can retain the import aliases?

Thanks in advance!

**Comment by sudo-suhas** [comment]
This issue is resolved in moq [`v0.2.0`](https://github.com/matryer/moq/releases/tag/v0.2.0).
