### ISSUE TITLE
Ignored method parameters cause errors on generation

### ISSUE THREAD

**Issue by heedson** [matryer/moq#70]
When a parameter is `_ *FooStruct` then the generation of the mock creates invalid `callInfo` struct.

Take the example of some gRPC service parameters that could look like:
```go
Foo(ctx context.Context, _ *types.Empty)
```
This will generate a `callInfo` that looks like:
```go
	callInfo := struct {
		Ctx context.Context
		_   *types.Empty
	}{
		Ctx: ctx,
		_:   _,
	}
```
It also will then try to call the `mock.FooFunc(ctx, _)` which is also invalid.

What the desired result is to have any `_` parameters ignore in the `callInfo` initialization stage (`_: _,` is invalid) and to replace the `_` in the FooFunc call with a `nil`.

If this is to support it for other types too, it may get more complex when trying to assign it to the default value of the incoming type.

**Comment by sudo-suhas** [comment]
This has been fixed via #131 and Moq now correctly handles the scenario where one of the parameters is using the blank identifier.
