### ISSUE TITLE
Add check that method was invoked 

### ISSUE THREAD

**Issue by s7anley** [matryer/moq#9]
During reading [Building WTF Dial](https://medium.com/@benbjohnson/wtf-dial-domain-model-9655cd523182#.qw25yhfk8), I found improved version of interface mocking. Structs contains also boolean fields for each method. These fields indicates if method was invoked or not. See [benbjohnson/wtf/mock.go](https://github.com/benbjohnson/wtf/blob/master/mock/mock.go). 

Is it something I can start working and add to moq? What's your option about it.

**Comment by matryer** [comment]
You can do this in user land:

```
func TestSomething(t *testing.T) {
    m := &mockedThing{}
}
```

**Comment by s7anley** [comment]
Sure, that's why I asked before start working on it.
