### ISSUE TITLE
Cyclic dependency with go modules when using other types from same package

### ISSUE THREAD

**Issue by omarkohl** [matryer/moq#92]
It is best demonstrated with an example.

Create a directory e.g. */tmp/mock-test* (**IMPORTANT** Outside your GOPATH) and place the following two files in it:

### foo.go
```go
package foo

type Foo interface{
	FooIt(bar *Bar)
}

type Bar struct{}
```

### go.mod
```
module github.com/omarkohl/foo
```

Then execute:

```
moq -out foo_moq_test.go . Foo
```

The resulting file contains and uses an erroneous import:

### foo_moq_test.go

```go
// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package foo

import (
	"github.com/omarkohl/foo"
	"sync"
)

var (
	lockFooMockFooIt sync.RWMutex
)

// Ensure, that FooMock does implement Foo.
// If this is not the case, regenerate this file with moq.
var _ Foo = &FooMock{}

// ...

type FooMock struct {
	// FooItFunc mocks the FooIt method.
	FooItFunc func(bar *foo.Bar)

	// calls tracks calls to the methods.
	calls struct {
		// FooIt holds details about calls to the FooIt method.
		FooIt []struct {
			// Bar is the bar argument value.
			Bar *foo.Bar
		}
	}
}

// ...
```

The *import* on line 7 should not be there because the Mock is already part of the same package.

This does *NOT* happen if the *Foo* interface does not use any type from the *foo* package.

### foo.go
```go
package foo

type Foo interface{
	FooIt()
}

type Bar struct{}
```

### foo_moq_test.go

```go
// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package foo

import (
	"sync"
)

var (
	lockFooMockFooIt sync.RWMutex
)

// Ensure, that FooMock does implement Foo.
// If this is not the case, regenerate this file with moq.
var _ Foo = &FooMock{}

// ...

type FooMock struct {
	// FooItFunc mocks the FooIt method.
	FooItFunc func()

	// calls tracks calls to the methods.
	calls struct {
		// FooIt holds details about calls to the FooIt method.
		FooIt []struct {
		}
	}
}

// ...
```

**Comment by IvanSafonov** [comment]
Yes, it's a bug. I didn't test this case. I'm creating mocks in the nested folder in my project. Like if I have package **project/package**, then mocks will be in **project/package/packagetest**.

I'll try to fix it soon. The only problem is that it has to be well tested with the unit tests. These tests need to be built only on go 1.11+, test packages has to be copied somewhere outside GOPATH, like tmp directory.
