### ISSUE TITLE
Variadic args are causing an issue with returning a slice

### ISSUE THREAD

**Issue by pehowell** [matryer/moq#99]
If you have a variadic method that returns a slice, such as:
```go
MultiSearch(ctx context.Context, searchTerms ...string) []string
```
moq tries to convert the return slice into a variadic parameter:
```go
MutiSearchFunc func(ctx context.Context, searchTerms ...string) ...string
```
which results in a `go/format` error, for example:
```
go/format: 52:79: expected type, found '...' (and 8 more errors)
```

I will submit a pull request shortly with a fix and test for returning slices that catches this issue.

Also, I just want to say thanks for moq!

**Comment by sudo-suhas** [comment]
Closed via #126
